/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary":                    "#a4ffb9",
        "on-primary":                 "#006532",
        "primary-dim":                "#00ed7e",
        "primary-fixed":              "#00fd87",
        "primary-fixed-dim":          "#00ed7e",
        "primary-container":          "#00fd87",
        "on-primary-container":       "#005b2c",
        "on-primary-fixed":           "#004621",
        "on-primary-fixed-variant":   "#006632",
        "secondary":                  "#00a9fd",
        "on-secondary":               "#00253c",
        "secondary-dim":              "#00a6f9",
        "secondary-fixed":            "#abd6ff",
        "secondary-fixed-dim":        "#8dcaff",
        "secondary-container":        "#006398",
        "on-secondary-container":     "#f4f8ff",
        "on-secondary-fixed":         "#003757",
        "on-secondary-fixed-variant": "#005583",
        "tertiary":                   "#ffbd5e",
        "on-tertiary":                "#5c3b00",
        "tertiary-dim":               "#ed9d00",
        "tertiary-fixed":             "#ffaa00",
        "tertiary-fixed-dim":         "#ed9d00",
        "tertiary-container":         "#ffaa00",
        "on-tertiary-container":      "#503200",
        "on-tertiary-fixed":          "#331f00",
        "on-tertiary-fixed-variant":  "#5c3a00",
        "error":                      "#ff716c",
        "on-error":                   "#490006",
        "error-dim":                  "#d7383b",
        "error-container":            "#9f0519",
        "on-error-container":         "#ffa8a3",
        "background":                 "#0e0e0e",
        "on-background":              "#ffffff",
        "surface":                    "#0e0e0e",
        "on-surface":                 "#ffffff",
        "surface-dim":                "#0e0e0e",
        "surface-bright":             "#2c2c2c",
        "surface-tint":               "#a4ffb9",
        "surface-variant":            "#262626",
        "on-surface-variant":         "#adaaaa",
        "surface-container-lowest":   "#000000",
        "surface-container-low":      "#131313",
        "surface-container":          "#1a1919",
        "surface-container-high":     "#201f1f",
        "surface-container-highest":  "#262626",
        "outline":                    "#777575",
        "outline-variant":            "#494847",
        "inverse-primary":            "#006e37",
        "inverse-surface":            "#fcf8f8",
        "inverse-on-surface":         "#565554",
        "purple-400":                 "#c084fc",
      },
      borderRadius: {
        none:    "0px",
        DEFAULT: "0px",
        sm:      "0px",
        md:      "0px",
        lg:      "0px",
        xl:      "0px",
        "2xl":   "0px",
        "3xl":   "0px",
        full:    "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body:     ["Space Grotesk", "sans-serif"],
        label:    ["Space Grotesk", "sans-serif"],
        mono:     ["Space Grotesk", "ui-monospace", "monospace"],
      },
    },
  },
  plugins: [],
};
